### PR TITLE
16.0 mig agreement legal

### PR DESCRIPTION
**Pull request by urvisha-serpentcs**

### CODE REVIEW

**Comment by sanchonuria** [comment]
Can you add the commits from #9 please?

**Review by len-foss — APPROVED** [review]
LGTM

**Comment by len-foss** [comment]
Hello @ygol 
Is it possible to move forward with this?

Besides the PR mentioned above, it would be nice to make the create method work in batch, split the create_agreement function into a method with only the logic and one that does the view stuff (for cleaner overrides, instead of doing `self.env[res["res_model"]].browse(res["res_id"])`...).

Also, comment all the settings that refer to modules that haven't been migrated, and other modules depend on this one (e.g. agreement_project).

**Comment by ygol** [comment]
> Hello @ygol Is it possible to move forward with this?
> 
> Besides the PR mentioned above, it would be nice to make the create method work in batch, split the create_agreement function into a method with only the logic and one that does the view stuff (for cleaner overrides, instead of doing `self.env[res["res_model"]].browse(res["res_id"])`...).
> 
> Also, comment all the settings that refer to modules that haven't been migrated, and other modules depend on this one (e.g. agreement_project).

Hi @len-foss I believe this PR was opened by @urvisha-serpentcs . Right?

**Comment by len-foss** [comment]
Right, it seems the work is done so the only thing left is a maintainer review/merge the PR. Did I get something wrong?

**Comment by ygol** [comment]
> Right, it seems the work is done so the only thing left is a maintainer review/merge the PR. Did I get something wrong?

oh no. sorry for the confusion. it just you made some recommendation/remarks in your review and I thought you asked me to address them.

**Comment by rousseldenis** [comment]
@urvisha-serpentcs Could you just put the version change in __manifest__.py in migration commit and not in pre-commit one ? Thanks

**Comment by rousseldenis** [comment]
@JayVora-SerpentCS

**Comment by SkiBY** [comment]
@urvisha-serpentcs there are some test cases covered in [PR#](https://github.com/OCA/agreement/pull/16) you can use to increase score.

**Review by SkiBY — APPROVED** [review]
LGTM
Code coverage to be increased

**Review by AntoniRomera — APPROVED** [review]
LGTM

**Review by sanchonuria — CHANGES_REQUESTED** [review]
Can you add the commits from https://github.com/OCA/agreement/pull/9 please?

**Comment by len-foss** [comment]
Honestly the simpler way would be to merge the PR, and then do another PR to bring #9 and/or other fixes.

 @rousseldenis do you have merge rights?

**Comment by rousseldenis** [comment]
> Honestly the simpler way would be to merge the PR, and then do another PR to bring #9 and/or other fixes.
> 
> @rousseldenis do you have merge rights?

Indeed we can do a further PR

/ocabot merge nobump

**Comment by len-foss** [comment]
Thank you!

**Pull request merged**
