### PR TITLE
16.0 [MIG] agreement_project

### PR DESCRIPTION
**Pull request by len-foss**

### CODE REVIEW

**Comment by rousseldenis** [comment]
/ocabot migration agreement_project

@len-foss Great to see you again!

**Comment by rousseldenis** [comment]
@len-foss In order to easy review, you can embed depending PRs here.

Following https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by len-foss** [comment]
Hello @rousseldenis ! Same here!
Thank you for the tip, I was indeed wondering how to do that.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by FrancoMaxime — APPROVED** [review]
code review

**Comment by len-foss** [comment]
@rousseldenis could this be merged?

**Pull request closed without merging**
