### PR TITLE
[17.0][MIG] agreement_sale: Migration to 17.0

### PR DESCRIPTION
**Pull request by imlopes**
Depends on: 

- [x] https://github.com/OCA/agreement/pull/35

### CODE REVIEW

**Review by yankinmax — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by rousseldenis** [comment]
@imlopes

**Comment by imlopes** [comment]
@rousseldenis Can you try the merge ?

**Comment by imlopes** [comment]
@rousseldenis @max3903 
Can we have this module merged ?
Thanks a lot.

**Comment by imlopes** [comment]
🙏 @max3903

**Pull request merged**
