### PR TITLE
[17.0][MIG] agreement_account: Migration to 17.0

### PR DESCRIPTION
**Pull request by imlopes**
Depends on: 

agreement: https://github.com/OCA/agreement/pull/35

### CODE REVIEW

**Review by yankinmax — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by rousseldenis** [comment]
@imlopes Could you remove test dependency as #35 has been merged ?

**Comment by imlopes** [comment]
@rousseldenis Can you retry the merge ?

**Comment by rousseldenis** [comment]
> @rousseldenis Can you retry the merge ?

I didn't before :sweat_smile:

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
